version: "3.7"

services:

  node-app:
    container_name: node-app 
    build: .
    volumes: 
      - ./src:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - node-mysql
    networks:
      - node-bridge

  node-mysql:
    container_name: node-mysql
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=node-api
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - node-bridge

networks:
    node-bridge:
      driver: bridge

