version: '2'
services:
  node_app:
    container_name: node_app 
    build: .
    volumes: 
      - .:/usr/app
      - ./src:/usr/app/src
      - /usr/app/src/node_modules
    ports:
      - "3000:3000"